# Generated by Django 4.1.6 on 2023-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
